// import { ObjectOf } from 'utils/types'
// import map_constants from 'constants/map_constants.asm'

// const getMatches = (input: string, regex: RegExp) => {
//   const matches = []
//   let match
//   while ((match = regex.exec(input))) {
//     matches.push(match)
//   }
//   return matches
// }

// const mapConstRegex = /mapconst ([A-Z_0-9]*),[ ]*([0-9]*),[ ]*([0-9]*)/g

// export const MAP_CONSTANTS: ObjectOf<{ width: number; height: number }> = getMatches(
//   map_constants,
//   mapConstRegex,
// ).reduce(
//   (result, [, name, height, width]) =>
//     name.includes('UNUSED')
//       ? result
//       : {
//           ...result,
//           [name]: { width: Number(width), height: Number(height) },
//         },
//   {},
// )

export const MAP_CONSTANTS = {
  PALLET_TOWN: { width: 10, height: 9 },
  VIRIDIAN_CITY: { width: 20, height: 18 },
  PEWTER_CITY: { width: 20, height: 18 },
  CERULEAN_CITY: { width: 20, height: 18 },
  LAVENDER_TOWN: { width: 10, height: 9 },
  VERMILION_CITY: { width: 20, height: 18 },
  CELADON_CITY: { width: 25, height: 18 },
  FUCHSIA_CITY: { width: 20, height: 18 },
  CINNABAR_ISLAND: { width: 10, height: 9 },
  INDIGO_PLATEAU: { width: 10, height: 9 },
  SAFFRON_CITY: { width: 20, height: 18 },
  ROUTE_1: { width: 10, height: 18 },
  ROUTE_2: { width: 10, height: 36 },
  ROUTE_3: { width: 35, height: 9 },
  ROUTE_4: { width: 45, height: 9 },
  ROUTE_5: { width: 10, height: 18 },
  ROUTE_6: { width: 10, height: 18 },
  ROUTE_7: { width: 10, height: 9 },
  ROUTE_8: { width: 30, height: 9 },
  ROUTE_9: { width: 30, height: 9 },
  ROUTE_10: { width: 10, height: 36 },
  ROUTE_11: { width: 30, height: 9 },
  ROUTE_12: { width: 10, height: 54 },
  ROUTE_13: { width: 30, height: 9 },
  ROUTE_14: { width: 10, height: 27 },
  ROUTE_15: { width: 30, height: 9 },
  ROUTE_16: { width: 20, height: 9 },
  ROUTE_17: { width: 10, height: 72 },
  ROUTE_18: { width: 25, height: 9 },
  ROUTE_19: { width: 10, height: 27 },
  ROUTE_20: { width: 50, height: 9 },
  ROUTE_21: { width: 10, height: 45 },
  ROUTE_22: { width: 20, height: 9 },
  ROUTE_23: { width: 10, height: 72 },
  ROUTE_24: { width: 10, height: 18 },
  ROUTE_25: { width: 30, height: 9 },
  REDS_HOUSE_1F: { width: 4, height: 4 },
  REDS_HOUSE_2F: { width: 4, height: 4 },
  BLUES_HOUSE: { width: 4, height: 4 },
  OAKS_LAB: { width: 5, height: 6 },
  VIRIDIAN_POKECENTER: { width: 7, height: 4 },
  VIRIDIAN_MART: { width: 4, height: 4 },
  VIRIDIAN_SCHOOL: { width: 4, height: 4 },
  VIRIDIAN_HOUSE: { width: 4, height: 4 },
  VIRIDIAN_GYM: { width: 10, height: 9 },
  DIGLETTS_CAVE_EXIT: { width: 4, height: 4 },
  VIRIDIAN_FOREST_EXIT: { width: 5, height: 4 },
  ROUTE_2_HOUSE: { width: 4, height: 4 },
  ROUTE_2_GATE: { width: 5, height: 4 },
  VIRIDIAN_FOREST_ENTRANCE: { width: 5, height: 4 },
  VIRIDIAN_FOREST: { width: 17, height: 24 },
  MUSEUM_1F: { width: 10, height: 4 },
  MUSEUM_2F: { width: 7, height: 4 },
  PEWTER_GYM: { width: 5, height: 7 },
  PEWTER_HOUSE_1: { width: 4, height: 4 },
  PEWTER_MART: { width: 4, height: 4 },
  PEWTER_HOUSE_2: { width: 4, height: 4 },
  PEWTER_POKECENTER: { width: 7, height: 4 },
  MT_MOON_1: { width: 20, height: 18 },
  MT_MOON_2: { width: 14, height: 14 },
  MT_MOON_3: { width: 20, height: 18 },
  TRASHED_HOUSE: { width: 4, height: 4 },
  CERULEAN_HOUSE_1: { width: 4, height: 4 },
  CERULEAN_POKECENTER: { width: 7, height: 4 },
  CERULEAN_GYM: { width: 5, height: 7 },
  BIKE_SHOP: { width: 4, height: 4 },
  CERULEAN_MART: { width: 4, height: 4 },
  MT_MOON_POKECENTER: { width: 7, height: 4 },
  TRASHED_HOUSE_COPY: { width: 4, height: 4 },
  ROUTE_5_GATE: { width: 4, height: 3 },
  PATH_ENTRANCE_ROUTE_5: { width: 4, height: 4 },
  DAYCAREM: { width: 4, height: 4 },
  ROUTE_6_GATE: { width: 4, height: 3 },
  PATH_ENTRANCE_ROUTE_6: { width: 4, height: 4 },
  PATH_ENTRANCE_ROUTE_6_COPY: { width: 4, height: 4 },
  ROUTE_7_GATE: { width: 3, height: 4 },
  PATH_ENTRANCE_ROUTE_7: { width: 4, height: 4 },
  PATH_ENTRANCE_ROUTE_7_COPY: { width: 4, height: 4 },
  ROUTE_8_GATE: { width: 3, height: 4 },
  PATH_ENTRANCE_ROUTE_8: { width: 4, height: 4 },
  ROCK_TUNNEL_POKECENTER: { width: 7, height: 4 },
  ROCK_TUNNEL_1: { width: 20, height: 18 },
  POWER_PLANT: { width: 20, height: 18 },
  ROUTE_11_GATE_1F: { width: 4, height: 5 },
  DIGLETTS_CAVE_ENTRANCE: { width: 4, height: 4 },
  ROUTE_11_GATE_2F: { width: 4, height: 4 },
  ROUTE_12_GATE_1F: { width: 5, height: 4 },
  BILLS_HOUSE: { width: 4, height: 4 },
  VERMILION_POKECENTER: { width: 7, height: 4 },
  POKEMON_FAN_CLUB: { width: 4, height: 4 },
  VERMILION_MART: { width: 4, height: 4 },
  VERMILION_GYM: { width: 5, height: 9 },
  VERMILION_HOUSE_1: { width: 4, height: 4 },
  VERMILION_DOCK: { width: 14, height: 6 },
  SS_ANNE_1: { width: 20, height: 9 },
  SS_ANNE_2: { width: 20, height: 9 },
  SS_ANNE_3: { width: 10, height: 3 },
  SS_ANNE_4: { width: 15, height: 4 },
  SS_ANNE_5: { width: 10, height: 7 },
  SS_ANNE_6: { width: 7, height: 8 },
  SS_ANNE_7: { width: 3, height: 4 },
  SS_ANNE_8: { width: 12, height: 8 },
  SS_ANNE_9: { width: 12, height: 8 },
  SS_ANNE_10: { width: 12, height: 8 },
  VICTORY_ROAD_1: { width: 10, height: 9 },
  LANCES_ROOM: { width: 13, height: 13 },
  HALL_OF_FAME: { width: 5, height: 4 },
  UNDERGROUND_PATH_NS: { width: 4, height: 24 },
  CHAMPIONS_ROOM: { width: 4, height: 4 },
  UNDERGROUND_PATH_WE: { width: 25, height: 4 },
  CELADON_MART_1: { width: 10, height: 4 },
  CELADON_MART_2: { width: 10, height: 4 },
  CELADON_MART_3: { width: 10, height: 4 },
  CELADON_MART_4: { width: 10, height: 4 },
  CELADON_MART_ROOF: { width: 10, height: 4 },
  CELADON_MART_ELEVATOR: { width: 2, height: 2 },
  CELADON_MANSION_1: { width: 4, height: 6 },
  CELADON_MANSION_2: { width: 4, height: 6 },
  CELADON_MANSION_3: { width: 4, height: 6 },
  CELADON_MANSION_4: { width: 4, height: 6 },
  CELADON_MANSION_5: { width: 4, height: 4 },
  CELADON_POKECENTER: { width: 7, height: 4 },
  CELADON_GYM: { width: 5, height: 9 },
  GAME_CORNER: { width: 10, height: 9 },
  CELADON_MART_5: { width: 10, height: 4 },
  CELADON_PRIZE_ROOM: { width: 5, height: 4 },
  CELADON_DINER: { width: 5, height: 4 },
  CELADON_HOUSE: { width: 4, height: 4 },
  CELADON_HOTEL: { width: 7, height: 4 },
  LAVENDER_POKECENTER: { width: 7, height: 4 },
  POKEMONTOWER_1: { width: 10, height: 9 },
  POKEMONTOWER_2: { width: 10, height: 9 },
  POKEMONTOWER_3: { width: 10, height: 9 },
  POKEMONTOWER_4: { width: 10, height: 9 },
  POKEMONTOWER_5: { width: 10, height: 9 },
  POKEMONTOWER_6: { width: 10, height: 9 },
  POKEMONTOWER_7: { width: 10, height: 9 },
  LAVENDER_HOUSE_1: { width: 4, height: 4 },
  LAVENDER_MART: { width: 4, height: 4 },
  LAVENDER_HOUSE_2: { width: 4, height: 4 },
  FUCHSIA_MART: { width: 4, height: 4 },
  FUCHSIA_HOUSE_1: { width: 4, height: 4 },
  FUCHSIA_POKECENTER: { width: 7, height: 4 },
  FUCHSIA_HOUSE_2: { width: 5, height: 4 },
  SAFARI_ZONE_ENTRANCE: { width: 4, height: 3 },
  FUCHSIA_GYM: { width: 5, height: 9 },
  FUCHSIA_MEETING_ROOM: { width: 7, height: 4 },
  SEAFOAM_ISLANDS_2: { width: 15, height: 9 },
  SEAFOAM_ISLANDS_3: { width: 15, height: 9 },
  SEAFOAM_ISLANDS_4: { width: 15, height: 9 },
  SEAFOAM_ISLANDS_5: { width: 15, height: 9 },
  VERMILION_HOUSE_2: { width: 4, height: 4 },
  FUCHSIA_HOUSE_3: { width: 4, height: 4 },
  MANSION_1: { width: 15, height: 14 },
  CINNABAR_GYM: { width: 10, height: 9 },
  CINNABAR_LAB_1: { width: 9, height: 4 },
  CINNABAR_LAB_2: { width: 4, height: 4 },
  CINNABAR_LAB_3: { width: 4, height: 4 },
  CINNABAR_LAB_4: { width: 4, height: 4 },
  CINNABAR_POKECENTER: { width: 7, height: 4 },
  CINNABAR_MART: { width: 4, height: 4 },
  CINNABAR_MART_COPY: { width: 4, height: 4 },
  INDIGO_PLATEAU_LOBBY: { width: 8, height: 6 },
  COPYCATS_HOUSE_1F: { width: 4, height: 4 },
  COPYCATS_HOUSE_2F: { width: 4, height: 4 },
  FIGHTING_DOJO: { width: 5, height: 6 },
  SAFFRON_GYM: { width: 10, height: 9 },
  SAFFRON_HOUSE_1: { width: 4, height: 4 },
  SAFFRON_MART: { width: 4, height: 4 },
  SILPH_CO_1F: { width: 15, height: 9 },
  SAFFRON_POKECENTER: { width: 7, height: 4 },
  SAFFRON_HOUSE_2: { width: 4, height: 4 },
  ROUTE_15_GATE_1F: { width: 4, height: 5 },
  ROUTE_15_GATE_2F: { width: 4, height: 4 },
  ROUTE_16_GATE_1F: { width: 4, height: 7 },
  ROUTE_16_GATE_2F: { width: 4, height: 4 },
  ROUTE_16_HOUSE: { width: 4, height: 4 },
  ROUTE_12_HOUSE: { width: 4, height: 4 },
  ROUTE_18_GATE_1F: { width: 4, height: 5 },
  ROUTE_18_GATE_2F: { width: 4, height: 4 },
  SEAFOAM_ISLANDS_1: { width: 15, height: 9 },
  ROUTE_22_GATE: { width: 5, height: 4 },
  VICTORY_ROAD_2: { width: 15, height: 9 },
  ROUTE_12_GATE_2F: { width: 4, height: 4 },
  VERMILION_HOUSE_3: { width: 4, height: 4 },
  DIGLETTS_CAVE: { width: 20, height: 18 },
  VICTORY_ROAD_3: { width: 15, height: 9 },
  ROCKET_HIDEOUT_1: { width: 15, height: 14 },
  ROCKET_HIDEOUT_2: { width: 15, height: 14 },
  ROCKET_HIDEOUT_3: { width: 15, height: 14 },
  ROCKET_HIDEOUT_4: { width: 15, height: 12 },
  ROCKET_HIDEOUT_ELEVATOR: { width: 3, height: 4 },
  SILPH_CO_2F: { width: 15, height: 9 },
  SILPH_CO_3F: { width: 15, height: 9 },
  SILPH_CO_4F: { width: 15, height: 9 },
  SILPH_CO_5F: { width: 15, height: 9 },
  SILPH_CO_6F: { width: 13, height: 9 },
  SILPH_CO_7F: { width: 13, height: 9 },
  SILPH_CO_8F: { width: 13, height: 9 },
  MANSION_2: { width: 15, height: 14 },
  MANSION_3: { width: 15, height: 9 },
  MANSION_4: { width: 15, height: 14 },
  SAFARI_ZONE_EAST: { width: 15, height: 13 },
  SAFARI_ZONE_NORTH: { width: 20, height: 18 },
  SAFARI_ZONE_WEST: { width: 15, height: 13 },
  SAFARI_ZONE_CENTER: { width: 15, height: 13 },
  SAFARI_ZONE_REST_HOUSE_1: { width: 4, height: 4 },
  SAFARI_ZONE_SECRET_HOUSE: { width: 4, height: 4 },
  SAFARI_ZONE_REST_HOUSE_2: { width: 4, height: 4 },
  SAFARI_ZONE_REST_HOUSE_3: { width: 4, height: 4 },
  SAFARI_ZONE_REST_HOUSE_4: { width: 4, height: 4 },
  UNKNOWN_DUNGEON_2: { width: 15, height: 9 },
  UNKNOWN_DUNGEON_3: { width: 15, height: 9 },
  UNKNOWN_DUNGEON_1: { width: 15, height: 9 },
  NAME_RATERS_HOUSE: { width: 4, height: 4 },
  CERULEAN_HOUSE_2: { width: 4, height: 4 },
  ROCK_TUNNEL_2: { width: 20, height: 18 },
  SILPH_CO_9F: { width: 13, height: 9 },
  SILPH_CO_10F: { width: 8, height: 9 },
  SILPH_CO_11F: { width: 9, height: 9 },
  SILPH_CO_ELEVATOR: { width: 2, height: 2 },
  TRADE_CENTER: { width: 5, height: 4 },
  COLOSSEUM: { width: 5, height: 4 },
  LORELEIS_ROOM: { width: 5, height: 6 },
  BRUNOS_ROOM: { width: 5, height: 6 },
  AGATHAS_ROOM: { width: 5, height: 6 },
}
